### ISSUE TITLE
Use more predictable filename for temporary files

### ISSUE THREAD

**Issue by craigbarnes** [tihirvon/dex#28]
I just noticed that dex creates a temporary file when writing changes, which creates quite a lot of noise when using [`inotify`](http://man7.org/linux/man-pages/man7/inotify.7.html) to monitor a directory. I would like to tell [`inotifywait`](http://linux.die.net/man/1/inotifywait) to exclude these temporary files, but the filenames are currently quite hard to match reliably with just a POSIX regexp, since the extension name is a random string. Would it be possible to add something like `.tmp` to the filenames, e.g. `file.txt.dapQ0O.tmp` instead of just `file.txt.dapQ0O`?

**Comment by tihirvon** [comment]
mkstemp(3):
"The last six characters of template must  be  "XXXXXX"  and  these  are
replaced  with  a string that makes the filename unique."

But .tmp.file.txt.dapQ0O would work.

**Comment by craigbarnes** [comment]
> But .tmp.file.txt.dapQ0O would work.

That would work fine for me.

I was just working on a patch for `tmp_filename`, but when I went to test it, it seems files are now being modified in-place and it's not immediately obvious how to force dex to use a temp file.

**Comment by tihirvon** [comment]
You probably tried to create `.tmp./path/to/file.txt.XXXXXX` (I did at first). I just pushed a fix to this issue.

**Comment by craigbarnes** [comment]
Thanks for the patch. It's much easier to regexp match the temp files now.

> You probably tried to create .tmp./path/to/file.txt.XXXXXX (I did at first)

Yeah, that was it.
