### ISSUE TITLE
Strange cursor position with Thai characters

### ISSUE THREAD

**Issue by pepa65** [tihirvon/dex#34]
Hoping this is a bug that will be easy to fix:
When opening this UTF-8 sample file in dex and going with the cursor to the end of each line,
the cursor lines up with the end of the displayed characters, except in case of the Thai fonts (line 123-130). There the cursor is displayed way past the end of the characters.

**Comment by bugabinga** [comment]
Possible duplicate #22

**Comment by pepa65** [comment]
Indeed, same problem as #22 it seems to only happen with Thai characters. Some editors do this correctly, notably JED. jupp, vim, nano, pico, le and joe. Others have the same problem as dex, like e3 and diakonos,

I hope you will be able to fix this, as dex has a lot of potential, being not as byzantine as JED, jupp and joe (and vim) but way more capable than nano and pico.

**Comment by craigbarnes** [comment]
I guess this issue can be closed then...

**Comment by pepa65** [comment]
Switching this issue to #22 then? I wonder how the other projects manage to do it. Diakonos' author also said it was too hard to fix.

**Comment by craigbarnes** [comment]
> Switching this issue to #22 then?

Yeah, there's no need for 2 open issues for the same thing.

> I wonder how the other projects manage to do it. Diakonos' author also said it was too hard to fix.

By either having a lookup table of _all_ combining characters or using a Unicode library that does likewise. There's also the possible issue of incorrect assumptions and simplifications being made elsewhere in the codebase, which may take a lot of work to find and fix. It's not "too hard", but it may be more work than anyone is willing to undertake.
