### ISSUE TITLE
Some bindings not working

### ISSUE THREAD

**Issue by olmokramer** [tihirvon/dex#35]
I can't get a few bindings to work. See list below. Is this an issue on my end or are they just not supported?

``` sh
# does nothing:
C-/     ^/

# prints char as if ctrl wasn't pressed
C-\;    ^\;     C-.     ^.      C-tab   ^tab
```

**Comment by craigbarnes** [comment]
Most of those look like terminal limitations rather than something specific to dex. Using `showkey -a` is always a good way to see what keycodes are produced for different key combinations.

**Comment by olmokramer** [comment]
Aha! `showkey` showed that indeed the wrong characters were generated by my terminal. Thanks!
