### ISSUE TITLE
make `delete-eol` can be config to kill a new line.

### ISSUE THREAD

**Issue by zw963** [tihirvon/dex#40]
In very many editor, e.g. emacs, nano, exist following spec:

### follow when press cmd_delete_eol
```sh
aaaaaaaa
|abcdabcd
bbbbbb
```
### will result:
```sh
aaaaaaaa
|
bbbbbbb
```
### when press cmd_delete_eol hotkey again
```sh
aaaaaaaaa
|bbbbbbbbb
```

In current version, the second step we have to use `cmd_delete` to do same things

Thanks.

**Comment by pepa65** [comment]
Should this be added to the behaviour of cmd_delete_eol, or should that be left alone (to not break backwards compatibility or users' muscle memory) and a new command cmd_deletetoo_eol be made? Or, can it be solved with the command language, to make a command with that behaviour??

**Comment by zw963** [comment]
> Should this be added to the behaviour of cmd_delete_eol, or should that be left alone (to not break backwards compatibility or users' muscle memory) and a new command cmd_deletetoo_eol be made?

I think should be add as a new command, we could rebinding old `cmd_delete_eol` with new `binding` use config file.

> can it be solved with the command language, to make a command with that behaviour??
This issue is create long long ago, I don't remember this editor support command language?

**Comment by pepa65** [comment]
Note that further development of the codebase is occurring in https://github.com/dte-editor/dte !! This feature will be implemented by adding a commandline option to the current `delete-eol` command.

**Comment by zw963** [comment]
> Note that further development of the codebase is occurring in https://github.com/dte-editor/dte !! This feature will be implemented by adding a commandline option to the current delete-eol command.

thanks, started that project.

I hope dte project can be target as a nano replacement for working in VPS or remote machine.

**Comment by craigbarnes** [comment]
This feature has been implemented in the [dte](https://github.com/dte-editor/dte) fork as `delete-eol -n`, in commit [23bd31c237](https://github.com/dte-editor/dte/commit/23bd31c2372c2d0a27f7bc3afca23339f9b0e934)

**Comment by zw963** [comment]
ok, I will follow that project.
